### ISSUE TITLE
Error when using "logback" as the logging_system

### ISSUE THREAD

**Issue by michaelajr** [trinidad/trinidad_logging_extension#2]
LoadError: no such file to load -- trinidad_logging_system_extension

Here is my config:

extensions:
    logging:
        config: config/trinidad-logging.xml
    logging_system: logback

Then....

% jruby -S trinidad

LoadError: no such file to load -- trinidad_logging_system_extension
                      require at org/jruby/RubyKernel.java:1019
                      require at /Users/Michael/.rbenv/versions/jruby-1.7.0/lib/ruby/shared/rubygems/custom_require.rb:36
               load_extension at /Users/Michael/.rbenv/versions/jruby-1.7.0/lib/ruby/gems/shared/gems/trinidad-1.4.4/lib/trinidad/extensions.rb:47
                    extension at /Users/Michael/.rbenv/versions/jruby-1.7.0/lib/ruby/gems/shared/gems/trinidad-1.4.4/lib/trinidad/extensions.rb:41
  configure_server_extensions at /Users/Michael/.rbenv/versions/jruby-1.7.0/lib/ruby/gems/shared/gems/trinidad-1.4.4/lib/trinidad/extensions.rb:14
                         each at org/jruby/RubyHash.java:1192
  configure_server_extensions at /Users/Michael/.rbenv/versions/jruby-1.7.0/lib/ruby/gems/shared/gems/trinidad-1.4.4/lib/trinidad/extensions.rb:13
           load_tomcat_server at /Users/Michael/.rbenv/versions/jruby-1.7.0/lib/ruby/gems/shared/gems/trinidad-1.4.4/lib/trinidad/server.rb:36
                   initialize at /Users/Michael/.rbenv/versions/jruby-1.7.0/lib/ruby/gems/shared/gems/trinidad-1.4.4/lib/trinidad/server.rb:11
                       (root) at /Users/Michael/.rbenv/versions/jruby-1.7.0/lib/ruby/gems/shared/gems/trinidad-1.4.4/bin/trinidad:6
                         load at org/jruby/RubyKernel.java:1045
                       (root) at /Users/Michael/.rbenv/versions/jruby-1.7.0/bin/trinidad:23

**Comment by michaelajr** [comment]
Never mind. Sorry. There is an indention issue in your README's trinidad.yml example. Need to indent the logging_system under the logging extension.

**Comment by kares** [comment]
Hi Michael, feel free to (fork and) edit the README via github to fix the indention ... it should create a PR
